# Generated by Django 5.2.2 on 2025-06-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_film_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
