# Generated by Django 5.2.2 on 2025-06-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_spectator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, to='core.film'),
        ),
    ]
