# Generated by Django 5.2.3 on 2025-06-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_spectator_favorite_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectator',
            name='name',
        ),
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('released', 'Released'), ('project', 'Project'), ('archived', 'Archived')], max_length=10),
        ),
    ]
