# Generated by Django 5.2.3 on 2025-06-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_author_user_author_id_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin'), ('tmdb', 'TMDb')], default='admin', max_length=10),
        ),
    ]
