# Generated by Django 5.2.3 on 2025-07-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_film_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='backdrop_path',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='poster_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
