# Generated by Django 5.2.3 on 2025-07-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_film_backdrop_path_film_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
