# Generated by Django 5.2.4 on 2025-07-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_film_backdrop_path_alter_film_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='poster_path',
        ),
        migrations.AddField(
            model_name='film',
            name='poster_original',
            field=models.ImageField(blank=True, null=True, upload_to='posters/originals/'),
        ),
    ]
